/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_crypto_plus_provider_base_FastJNIBuffer */

#ifndef _Included_com_ibm_crypto_plus_provider_base_FastJNIBuffer
#define _Included_com_ibm_crypto_plus_provider_base_FastJNIBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_crypto_plus_provider_base_FastJNIBuffer
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_base_FastJNIBuffer_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
